### ISSUE TITLE
Buffer completion fails with candidates at a distance greater than 10 lines

### ISSUE THREAD

**Issue by petobens** [Shougo/neocomplete.vim#290]
Consider the following minimal vimrc

    set nocompatible

    let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
    let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

    set runtimepath=$DOTVIM,$VIMRUNTIME
    set runtimepath+=$DOTVIM/bundle/ultisnips
    set runtimepath+=$DOTVIM/bundle/neocomplete

    filetype plugin indent on
    let g:tex_flavor = 'latex'
    set number

    let g:UltiSnipsSnippetDirectories = ["testsnippet"]

    let g:neocomplete#enable_at_startup = 1
    if !exists('g:neocomplete#keyword_patterns')
        let g:neocomplete#keyword_patterns = {}
    endif
    let keyword_patterns = {}
    let keyword_patterns = {'tex' : '\h\w\{,2}:\%(\w*\|\w*_\w*\)\?'}
    call neocomplete#custom#source('buffer', 'keyword_patterns', keyword_patterns)

and create two files: i) a snippet file,`$DOTVIM/testsnippet/tex.snippets`:

	snippet crp "Cleverref proposition" w
	\cref{pro:${1}}$0
	endsnippet

and ii) a tex file, `$HOME/Desktop/test.tex`:

    \label{pro:first}
    \label{pro:second}
    \label{pro:third}

    % Try completing in the next lines (i.e starting from the 11th line):

Note that the comment  `% Try completing in the next lines (i.e starting from the 11th line)` is in the 10th line of `test.tex` file.

Now open `test.tex` with Gvim and place the cursor in insert mode at the 11th line (i.e below the comment). Type `crp` and press `<TAB>` to expand the snippet. As it can be seen in the GIF neocomplete popup will correctly show the three candidates: `pro:first`, `pro:second` and `pro:third`. Press `<ESC>` to quit both insert mode and the popup and then `o` to get to a new line. In that line (12th line) type once again `crp` and press `<TAB>` to expand the snippet. As it can be seen in the GIF neocomplete popup will now only show two candidates `pro:second` and `pro:third`. I think this is because `pro:first` candidate is a distance of more than 10 lines and it seems that buffer completion only takes into account the previous 10 or less lines.  Indeed if you now press `<ESC>` to exit the popup menu, press `o` to get into a new line and in that line (13th line) type `crp` and press `<TAB>` to expand the snippet you will see that now the neocomplete popup only completes `pro:third`. 
Finally if you repeat the procedure but now on the 14th line then neocomplete popup is empty.

![http___makeagif com__media_9-11-2014_bfk6i8](https://cloud.githubusercontent.com/assets/2583971/4240473/29a22d1a-39eb-11e4-8a4d-afb973abdfb8.gif)

**Comment by petobens** [comment]
This problem is unfortunately back. Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/vimproc/
set runtimepath+=$DOTVIM/bundle/neocomplete/

filetype plugin indent on
let g:tex_flavor = 'latex'
set number

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
endif
let g:neocomplete#sources.tex = ['buffer']

let keyword_patterns = {}
let keyword_patterns = {'tex' : '\h\w\{,2}:\%(\w*\|\w*_\w*\)\?'}
call neocomplete#custom#source('buffer', 'keyword_patterns',
            \ keyword_patterns)

```
And create a `tex` file, `foo.tex`, like this (where the last empty line is line 15):

```tex
pro:first
pro:second
pro:third






% Try completing backwards (i.e starting from line 15, then line 14, ...)






```
Now, as in the GIF, start completing from line 15 backwards by typing `pro:`. You will see that there is no completion in line 15 and 14, that in line 13 only `pro:third` is completed, in line 12 only `pro:third` and `pro:second` and in line 11 all three `pro:third`, `pro:second` and `pro:third` are completed. I expected neocomplete to complete  `pro:third`, `pro:second` and `pro:third` always!

![blah](https://cloud.githubusercontent.com/assets/2583971/8512177/c23bbb8e-230d-11e5-86f3-1464424290dc.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
This is not fixed. With the same minimal vimrc as before create a `foo.tex` file that contains 

```tex
pro:first
pro:second
pro:third












pro:fourth
```
Where `pro:fourth` is in line 15. Now, as in the GIF open a vim or Gvim windows that has 10 lines of height. Then try completing somewhere between lines 4 and 14 (for instance in line 5), you will that after the first `pro:` (which doesn't bring any completion) neocomplete completes `pro:first`, `pro:second` and `pro:third` but not `pro:fourth`. Similarly if you now write the buffer (`:w) and then start completing below line 15, then neocomplete will once again not complete the first time and then only complete `pro:fourth` but not `pro:first`, `pro:second` and `pro:third`. I expect neocomplete to i) complete all entries in the buffer and not just the ones that are visible in the window and ii) start completing inmediately after a `:w` command (for some reason neocomplete doesn't complete in the first try).

![blah](https://cloud.githubusercontent.com/assets/2583971/8634170/7fc5fa1a-27c4-11e5-8788-0b5e789024f0.gif)

**Comment by Shougo** [comment]
Fixed the problem.

**Comment by petobens** [comment]
Thanks Shougo but now with the same minimal vimrc as before I get no completion at all:

![blah](https://cloud.githubusercontent.com/assets/2583971/8638266/2cfd6ba6-288c-11e5-9e04-ae30bbb19273.gif)

**Comment by Shougo** [comment]
Really?

I cannot reproduce the problem.
Please check the buffer source behavior.

**Comment by Shougo** [comment]
Oh, I get it.
It is feature.
You should execute `:NeoCompleteBufferMakeCache` command.
neocomplete only make cache automatically in Vim Window appeared candidates.
You must wait until make cache is completed.

**Comment by Shougo** [comment]
You should check `neocomplete#sources#buffer#make_cache_current_line()` behavior.

**Comment by Shougo** [comment]
Fixed it.

**Comment by petobens** [comment]
Hi @Shougo, sorry for the delay in my reply. Unfortunately this is still not working properly. With your latest changes I do get completion but I still have the problem that neocomplete will not show candidates that are not visible in the same window.
You can see in the following GIF that neocomplete will show the four candidates the first time, none the second time and only three candidates the third time. If I now save the buffer and then go down and start completing after the line that says `pro:fourth` (line 18(, neocomplete will only complete `pro:fourth`.
I expect neocomplete to always complete `pro:first, pro:second, pro:third, pro:fourth` and not just a subset of them. 

![blah2](https://cloud.githubusercontent.com/assets/2583971/8763131/aa739fdc-2d65-11e5-82ae-ddbdc3fccaf9.gif)

**Comment by Shougo** [comment]
> Hi @Shougo, sorry for the delay in my reply. Unfortunately this is still not working properly. With your latest changes I do get completion but I still have the problem that neocomplete will not show candidates that are not visible in the same window.

Unfortunatellcy, it is feature.
neocomplete will make cache in visible range automatically.
You should use `:NeoCompleteBufferMakeCache`.

**Comment by petobens** [comment]
Mmm okay. Shouldn't neocomplete **buffer** source cache the whole **buffer** rather than only the candidates in visible range?

**Comment by Shougo** [comment]
No.
neocomplete make cache whole range.
But the cache is slow in Windows environment.
I cannot fix the problem in neocomplete.
