### ISSUE TITLE
Neocomplete variable undefined

### ISSUE THREAD

**Issue by 4ydx** [Shougo/neocomplete.vim#424]
Apologies but I don't really understand what the issue is.  Any help is appreciated.

Error detected while processing function neocomplete#handler#_do_auto_complete..<SNR>84_check_fallback:
line    3:
E121: Undefined variable: neocomplete

**Comment by DoumanAsh** [comment]
It seems to happen with current master at the vim start. Seems to cease after short time(time issue?)

**Comment by barwinco** [comment]
yep. same error.

**Comment by dongli** [comment]
Similar error too in my Mac Mini, but no error in my MacBook Pro.

```
Error detected while processing function neocomplete#handler#_do_auto_complete..<SNR>60_check_fallback:
line    3:
E121: Undefined variable: neocomplete
Press ENTER or type command to continue
Error detected while processing function neocomplete#handler#_do_auto_complete..<SNR>60_check_fallback:
line    3:
E15: Invalid expression: empty(g:neocomplete#fallback_mappings) && len(matchstr(cur_text, '\h\w*$'))   >= g:neocomplete#auto_completion_start_length && !neocomplete.skip_next_complete && !neocomple
te#complete#_check_previous_position(      cur_text, complete_pos)
Press ENTER or type command to continue
```

**Comment by Shougo** [comment]
Fixed.  Thanks.

**Comment by barwinco** [comment]
Now we have another problem. For example:
```scss
header {
  color: #f5f5f5; 
  font-size: 3em;
}
```
if I try to change color (f5f5f5 > ffdaaa) by pressing 'cw' after '#':
```scss
header {
  color: #ffda<Plug>(neocomplete_fallback); 
  font-size: 3em;
}
```

**Comment by dongli** [comment]
@barwinco I also saw one such thing.

**Comment by Shougo** [comment]
@barwinco Please see the issue template.

**Comment by barwinco** [comment]
Gentoo Linux, :version
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 29 2015 10:06:20)
Included patches: 1-764
Modified by Gentoo-9999
Compiled by portage@workstation
Huge version without GUI.  Features included (+) or not (-):
+acl             +cindent         +conceal         +digraphs        +farsi           +gettext         +libcall         +mksession       +mouse_netterm   -mzscheme        +profile         +scrollbind      +syntax          +textobjects     +visualextra     +X11
+arabic          +clientserver    +cryptv          -dnd             +file_in_path    -hangul_input    +linebreak       +modify_fname    +mouse_sgr       +netbeans_intg   +python/dyn      +signs           +tag_binary      +title           +viminfo         +xfontset
+autocmd         +clipboard       +cscope          -ebcdic          +find_in_path    +iconv           +lispindent      +mouse           -mouse_sysmouse  +path_extra      +python3/dyn     +smartindent     +tag_old_static  -toolbar         +vreplace        -xim
-balloon_eval    +cmdline_compl   +cursorbind      +emacs_tags      +float           +insert_expand   +listcmds        -mouseshape      +mouse_urxvt     +perl            +quickfix        -sniff           -tag_any_white   +user_commands   +wildignore      +xsmp_interact
-browse          +cmdline_hist    +cursorshape     +eval            +folding         +jumplist        +localmap        +mouse_dec       +mouse_xterm     +persistent_undo +reltime         +startuptime     +tcl             +vertsplit       +wildmenu        +xterm_clipboard
++builtin_terms  +cmdline_info    +dialog_con      +ex_extra        -footer          +keymap          +lua             +mouse_gpm       +multi_byte      +postscript      +rightleft       +statusline      +terminfo        +virtualedit     +windows         -xterm_save
+byte_offset     +comments        +diff            +extra_search    +fork()          +langmap         +menu            -mouse_jsbterm   +multi_lang      +printer         +ruby            -sun_workshop    +termresponse    +visual          +writebackup     -xpm
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H     -march=bdver2 -O2 -pipe -fno-stack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/usr/include  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1
Linking: x86_64-pc-linux-gnu-gcc   -L. -Wl,-O1 -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--no-undefined -Wl,-E  -Wl,-O1 -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl  -L/usr/lib
-lluajit-5.1 -Wl,-E -Wl,-O1 -Wl,--as-needed  -L/usr/lib64/perl5/5.20.2/x86_64-linux/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lc   -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby22 -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib64
```
.vimrc (vim-plug plugins manager):
```viml
set nocompatible
set tw=10
set fo+=aw
syntax on
filetype plugin indent on
set encoding=utf-8
set autoindent
set autoread
set backspace=indent,eol,start
set hidden
set hlsearch
set ignorecase
set smartcase
set incsearch
set laststatus=2
set modeline
set nobackup
set noswapfile
set nowritebackup
set ruler
set scrolloff=3
set shiftwidth=4
set matchtime=4
set noshowmode
set smartindent
set t_Co=256
set expandtab
set smarttab
set tabstop=4
set wildignorecase
set breakindent
set nu
set ttyfast

call plug#begin('~/.vim/plugged')

Plug 'Shougo/neocomplete.vim'
let g:neocomplete#enable_at_startup                 = 1
let g:neocomplete#force_overwrite_completefunc      = 1
let g:neocomplete#enable_smart_case                 = 1
let g:neocomplete#auto_completion_start_length      = 3
let g:neocomplete#sources#syntax#min_keyword_length = 3
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

if has('conceal')
  set conceallevel=2 concealcursor=i
endif

call plug#end()
```
![](http://i.imgur.com/oZJbvKE.gif)

**Comment by ahmedelgabri** [comment]
I have the same exact issue after updating to the latest version.

**Comment by kiswa** [comment]
I have this problem as well. I use Vundle for plugin management and my neocomplete settings are:

```viml
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3
inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
```

**Comment by ahmedelgabri** [comment]
Here is my settings and I'm using vim-plug.

```viml
  " Neocomplete
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_smart_case = 1
  let g:neocomplete#sources#syntax#min_keyword_length = 3
  let g:neocomplete#auto_completion_start_length = 1
  let g:neocomplete#sources#buffer#cache_limit_size = 50000
  let g:neocomplete#data_directory = $HOME.'/.vim/cache/noecompl'
  let g:neocomplete#sources#syntax#min_keyword_length = 3
  if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
  endif
  let g:neocomplete#force_omni_input_patterns.javascript = '[^. \t]\.\w*'
  " Tab completion.
  inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

  aug omnicomplete
    au!
    au FileType css setl omnifunc=csscomplete#CompleteCSS
    au FileType markdown setl omnifunc=htmlcomplete#CompleteTags
    au FileType html,htmldjango,jinja setl omnifunc=emmet#completeTag
    au FileType javascript setl omnifunc=tern#Complete
    au FileType python setl omnifunc=pythoncomplete#Complete
    au FileType xml setl omnifunc=xmlcomplete#CompleteTags
  aug END
```

**Comment by DoumanAsh** [comment]
Guys i think it would be more right to create a separate issue for that. The previous one is fixed and it introduces another issue :)
Besides this one is already closed :)

**Comment by ahmedelgabri** [comment]
@DoumanAsh I don't think it's fixed. Cause I still see the same exact behaviour as @barwinco in his [gif](https://github.com/Shougo/neocomplete.vim/issues/424#issuecomment-116707789) which was supposed to be fixed.

**Comment by kiswa** [comment]
@ahmedelgabri I think it is a new issue that came from this fix based on how @barwinco phrased his comment.

Hopefully, @barwinco will open a new issue since he has the most detailed comment.

**Comment by Shougo** [comment]
@ahmedelgabri @barwinco 
It is not same problem in this issue and it is already fixed.

**Comment by ahmedelgabri** [comment]
Thanks @Shougo

**Comment by kiswa** [comment]
:+1:

**Comment by barwinco** [comment]
Thanks for your work, @Shougo. :gem:
